### ISSUE TITLE
Reconnect feature

### ISSUE THREAD

**Issue by RwbyChan** [ktanakaj/simple-ng-websocket#2]
Possible to add a reconnect feature? If socket gets closed or error that it tries to reconnect?

I tried myself quickly to just in the on close or on error event to just do `this.ngws.connect();`
but with this, if I get reconnected, I receive x amount of messages (message for each time it still wasnt connected) which obviously isn't good

**Comment by ktanakaj** [comment]
Thanks for your comment. I reproduce this action that onclose event and `this.ngws.connect();`.
I'll think a solution for this problem.
